### ISSUE TITLE
Can't install plugin: invalid filename returned by server

### ISSUE THREAD

**Issue by relgames** [Tirke/cup-plugin#1]
Trying to install the plugin in IDEA 2018.2.4, get an error: invalid filename returned by server

<img width="816" alt="screen shot 2018-10-05 at 14 20 56" src="https://user-images.githubusercontent.com/179605/46534901-034a5a00-c8aa-11e8-9c3a-0c0fb8ea1ae7.png">

<img width="400" alt="screen shot 2018-10-05 at 14 21 02" src="https://user-images.githubusercontent.com/179605/46534903-05141d80-c8aa-11e8-86bc-8fc36b39682e.png">

**Comment by Tirke** [comment]
I'm looking into it, thanks for the report.

**Comment by Tirke** [comment]
Should be good, I've uploaded a new build (v1.2) on Jetbrains repository.
