### ISSUE TITLE
Unable to load preference panel

### ISSUE THREAD

**Issue by baptistecdr** [Tirke/cup-plugin#2]
Hello,

Thank you for your extension but IntelliJ is unable to load the preference panel from your extension... I attached the complete stack trace. Hope that can help..

<img src="https://i.snipboard.io/dUQJhS.jpg" alt="preference panel" width="500px"/>

[stacktrace.txt](https://github.com/Tirke/cup-plugin/files/4485290/stacktrace.txt)

**Comment by Tirke** [comment]
Seems to work for me on Intellij 2021 + latest plugin version

**Comment by baptistecdr** [comment]
Indeed with the new version. 👍🏼
