### ISSUE TITLE
Cup Support marked as incompatible with the current version of the Intellij

### ISSUE THREAD

**Issue by chuck2098** [Tirke/cup-plugin#4]
Hi,
I get the follow error when I try to install Cup Support plugin in Intellij.

**Plugin 'Cup Support' (version 1.2) was explicitly marked as incompatible with the current version of the IDE**

Can I solve this?

Thanks

**Comment by Tirke** [comment]
Hello @chuck2098,

Yes you can if you want, just open a PR and I will submit the plugin.
Otherwise, I will do it when I have some time on my hands.

**Comment by Gargantua82** [comment]
i have the same problem, help me please

**Comment by Tirke** [comment]
I will push an updated version compatible with the latest Intellij version soon

**Comment by Tirke** [comment]
1.4 released and will work with recent Intellij versions.
